In [2]:
################################
# 1. libs
#

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [3]:
################################
# 2. load data
#

data = pd.read_csv('census_income_dataset_preprocessed.csv')

################################
# Do not read feature names (dataset header)
#

# df = pd.read_csv('census_income_dataset_preprocessed', header = None)

display(data.head(2))
print(type(data))

,age,workclass,education-num,marital-status,occupation,capital-gains,capital-loss,hours-per-week,native-country,target
0,39,6,13,4,0,2174,0,40,38,0
1,50,5,13,2,3,0,0,13,38,0

<class 'pandas.core.frame.DataFrame'>

In [4]:
################################
# 2. X, Y
#

# X = data.drop('target', axis = 1)
# Y = data['target']

X = data.iloc[:, :-1]
Y = data.iloc[:, -1]

print(X.shape, Y.shape)

display(X.head(2))
print('--------------------')
display(Y.head(2))

(32561, 9) (32561,)

,age,workclass,education-num,marital-status,occupation,capital-gains,capital-loss,hours-per-week,native-country
0,39,6,13,4,0,2174,0,40,38
1,50,5,13,2,3,0,0,13,38

--------------------

0    0
1    0
Name: target, dtype: int64

In [5]:
################################
# 3. test new dataframe
#

Z = pd.concat([X, Y], axis = 1)
Z.head(2)

,age,workclass,education-num,marital-status,occupation,capital-gains,capital-loss,hours-per-week,native-country,target
0,39,6,13,4,0,2174,0,40,38,0
1,50,5,13,2,3,0,0,13,38,0

In [6]:
################################
# 4. split train, dev, test
#

split_factor = 0.1

X_train_tmp, X_test, Y_train_tmp, Y_test = train_test_split(X, Y, test_size = split_factor, random_state = 101)

dev_size_factor = X_test.shape[0] / X_train_tmp.shape[0]

X_train, X_dev, Y_train, Y_dev = train_test_split(X_train_tmp, Y_train_tmp, test_size = dev_size_factor, random_state = 101)

print(X_train.shape, Y_train.shape)
print(X_dev.shape, Y_dev.shape)
print(X_test.shape, Y_test.shape)

display(X_train.head(2))

(26047, 9) (26047,)
(3257, 9) (3257,)
(3257, 9) (3257,)

,age,workclass,education-num,marital-status,occupation,capital-gains,capital-loss,hours-per-week,native-country
29069,58,5,10,0,9,0,0,40,38
21516,78,8,4,2,14,0,0,20,38

In [7]:
################################
# 5. define test sets
#

sets = ['Train', 'Dev', 'Test']
feature_sets = [X_train, X_dev, X_test]
target_sets = [Y_train, Y_dev, Y_test]

In [8]:
################################
# 6.1. model fit/predict - experiment 1
#

model = MLPClassifier(max_iter = 500, random_state = 101)
model.fit(X_train, Y_train)

scores = {}

for idx, set in enumerate(sets):
    Y_pred = model.predict(feature_sets[idx])    
    acc_score = accuracy_score(target_sets[idx], Y_pred)
    scores[set] = round(acc_score, 4)

print(scores)

{'Train': 0.8376, 'Dev': 0.8167, 'Test': 0.8299}

In [9]:
################################
# 6.2. model fit/predict - experiment 2
#

model = MLPClassifier(max_iter = 500, random_state = 101, hidden_layer_sizes = (100, 100))
model.fit(X_train, Y_train)

scores = {}

for idx, set in enumerate(sets):
    Y_pred = model.predict(feature_sets[idx])    
    acc_score = accuracy_score(target_sets[idx], Y_pred)
    scores[set] = round(acc_score, 4)

print(scores)

{'Train': 0.8607, 'Dev': 0.8265, 'Test': 0.8511}

In [10]:
################################
# 6.3. model fit/predict - experiment 3
#

model = MLPClassifier(max_iter = 500, random_state = 101, hidden_layer_sizes = (100, 100, 100))
model.fit(X_train, Y_train)

scores = {}

for idx, set in enumerate(sets):
    Y_pred = model.predict(feature_sets[idx])    
    acc_score = accuracy_score(target_sets[idx], Y_pred)
    scores[set] = round(acc_score, 4)

print(scores)

{'Train': 0.8517, 'Dev': 0.8311, 'Test': 0.8434}

In [11]:
################################
# 6.4. model fit/predict - experiment 4
#

model = MLPClassifier(max_iter = 500, random_state = 101, hidden_layer_sizes = (150, 150))
model.fit(X_train, Y_train)

scores = {}

for idx, set in enumerate(sets):
    Y_pred = model.predict(feature_sets[idx])    
    acc_score = accuracy_score(target_sets[idx], Y_pred)
    scores[set] = round(acc_score, 4)

print(scores)

{'Train': 0.8685, 'Dev': 0.8351, 'Test': 0.8468}

In [12]:
################################
# 6.5. model fit/predict - experiment 5
#

model = MLPClassifier(max_iter = 500, random_state = 101, hidden_layer_sizes = (50, 50))
model.fit(X_train, Y_train)

scores = {}

for idx, set in enumerate(sets):
    Y_pred = model.predict(feature_sets[idx])    
    acc_score = accuracy_score(target_sets[idx], Y_pred)
    scores[set] = round(acc_score, 4)

print(scores)

{'Train': 0.8327, 'Dev': 0.8139, 'Test': 0.825}