In [2]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import numpy as np
import matplotlib.pyplot as plt

In [3]:
##################################
# 1. Load dataset
#

dataset = sns.load_dataset('titanic')
dataset.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

In [4]:
##################################
# 2. Remove unwanted cols
#
# Features to include: sex, age, fare, class, embark_town, alone.

# drops = ['pclass', 'sibsp', 'parch', 'embarked', 'who', 'adult_male', 'deck', 'alive']
# for col in drops:
#     titanic = titanic.drop(col, axis = 1)
# titanic.head(2)

In [5]:
##################################
# 3. Shallow copy dataset for desired features
#

features_desired = ['sex', 'age', 'fare', 'class', 'embark_town', 'alone']

titanic = dataset[features_desired].copy()
titanic.head(2)

      sex   age     fare  class  embark_town  alone
0    male  22.0   7.2500  Third  Southampton  False
1  female  38.0  71.2833  First    Cherbourg  False

In [6]:
##################################
# 4. get column names
#

cols = titanic.columns.tolist()
cols

['sex', 'age', 'fare', 'class', 'embark_town', 'alone']

In [7]:
##################################
# 5. Detect NULL columns
#
# !Trick: This must be done before transforming text fields and filling nulls
#

for col in cols:
    sum = titanic[col].isnull().sum()
    if sum > 0:
        print(col, 'nulls', sum)

age nulls 177
embark_town nulls 2

In [8]:
titanic.shape

(891, 6)

In [9]:
##################################
# 6. value_counts()
#

for col in cols:
    count = titanic[col].value_counts()
    print('-------', count)

------- sex
male      577
female    314
Name: count, dtype: int64
------- age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64
------- fare
8.0500     43
13.0000    42
7.8958     38
7.7500     34
26.0000    31
           ..
35.0000     1
28.5000     1
6.2375      1
14.0000     1
10.5167     1
Name: count, Length: 248, dtype: int64
------- class
Third     491
First     216
Second    184
Name: count, dtype: int64
------- embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64
------- alone
True     537
False    354
Name: count, dtype: int64

In [10]:
age_mean = titanic['age'].mean()
age_mean = round(age_mean)
age_mean

30

In [11]:
##################################
# 7. Fill 'age' null with mean
#

titanic['age'] = titanic['age'].fillna(age_mean)
# titanic['age'].fillna(age_mean, inplace = True)
titanic['age'].isnull().sum()

0

In [12]:
##################################
# 8. Transform text fields
# TODO: Detect text fields
#

features_with_text = ['sex', 'class', 'embark_town', 'alone']

enc = LabelEncoder()

for col in features_with_text:
    titanic[col] = enc.fit_transform(titanic[col].astype('str'))

titanic.head(2)

   sex   age     fare  class  embark_town  alone
0    1  22.0   7.2500      2            2      0
1    0  38.0  71.2833      0            0      0

In [13]:
titanic.head(2)

   sex   age     fare  class  embark_town  alone
0    1  22.0   7.2500      2            2      0
1    0  38.0  71.2833      0            0      0

In [14]:
##################################
# 9. Draw histogram
#

# age = titanic['age']
# plt.hist(age)
# plt.show()

In [15]:
##################################
# 10. Detect outliers
#

features_of_concern = ['age', 'fare']

for col in features_of_concern:
    el = titanic[col]
    min_deviation = el.mean() - 3 * el.std()    
    max_deviation = el.mean() + 3 * el.std()

    X = titanic[el >= min_deviation]
    display(X.shape)

    X = titanic[el <= max_deviation]
    display(X.shape)

(891, 6)

(884, 6)

(891, 6)

(871, 6)

In [16]:
titanic.head(2)

   sex   age     fare  class  embark_town  alone
0    1  22.0   7.2500      2            2      0
1    0  38.0  71.2833      0            0      0

In [17]:
titanic.shape

(891, 6)

In [18]:
##################################
# 11. Normalize dataset
#

for col in cols:
    el = titanic[col]
    normalized = (el - el.std()) / (el.max() - el.min())
    titanic[col] = normalized

In [19]:
titanic.head(2)

       sex       age      fare     class  embark_town     alone
0  0.52201  0.113061 -0.082844  0.581964     0.401923 -0.489615
1 -0.47799  0.314117  0.042141 -0.418036    -0.264744 -0.489615