In [4]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

dataset = sns.load_dataset('tips')
display(dataset.head(2))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [6]:
type(dataset)

pandas.core.frame.DataFrame

In [8]:
dataset.keys()

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [24]:
tips = dataset.copy()

enc = LabelEncoder()
tips['sex'] = enc.fit_transform(tips['sex'].astype('str'))
tips['smoker'] = enc.fit_transform(tips['smoker'].astype('str'))
tips['day'] = enc.fit_transform(tips['day'].astype('str'))
tips['time'] = enc.fit_transform(tips['time'].astype('str'))

display(tips.head(1))
tips_normalized = (tips - tips.mean()) / (tips.max() - tips.min())
tips_normalized.head(10)

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2

   total_bill       tip       sex    smoker       day      time      size
0   -0.058566 -0.220920 -0.643443 -0.381148  0.086066 -0.278689 -0.113934
1   -0.197862 -0.148698  0.356557 -0.381148  0.086066 -0.278689  0.086066
2    0.025640  0.055747  0.356557 -0.381148  0.086066 -0.278689  0.086066
3    0.081568  0.034636  0.356557 -0.381148  0.086066 -0.278689 -0.113934
4    0.100630  0.067969 -0.643443 -0.381148  0.086066 -0.278689  0.286066
5    0.115292  0.190191  0.356557 -0.381148  0.086066 -0.278689  0.286066
6   -0.230749 -0.110920  0.356557 -0.381148  0.086066 -0.278689 -0.113934
7    0.148598  0.013525  0.356557 -0.381148  0.086066 -0.278689  0.286066
8   -0.099412 -0.115364  0.356557 -0.381148  0.086066 -0.278689 -0.113934
9   -0.104858  0.025747  0.356557 -0.381148  0.086066 -0.278689 -0.113934

In [20]:
tips_standized = (tips - tips.mean()) / tips.std()
tips_standized.head(10)

   total_bill       tip       sex    smoker       day      time      size
0   -0.314066 -1.436993 -1.340598 -0.783179  0.278585 -0.620307 -0.598961
1   -1.061054 -0.967217  0.742879 -0.783179  0.278585 -0.620307  0.452453
2    0.137497  0.362610  0.742879 -0.783179  0.278585 -0.620307  0.452453
3    0.437416  0.225291  0.742879 -0.783179  0.278585 -0.620307 -0.598961
4    0.539635  0.442111 -1.340598 -0.783179  0.278585 -0.620307  1.503867
5    0.618266  1.237116  0.742879 -0.783179  0.278585 -0.620307  1.503867
6   -1.237411 -0.721488  0.742879 -0.783179  0.278585 -0.620307 -0.598961
7    0.796869  0.087972  0.742879 -0.783179  0.278585 -0.620307  1.503867
8   -0.533108 -0.750398  0.742879 -0.783179  0.278585 -0.620307 -0.598961
9   -0.562313  0.167472  0.742879 -0.783179  0.278585 -0.620307 -0.598961

In [22]:
dataset.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3